### ISSUE TITLE
cards and buttons color

### ISSUE THREAD

**Issue by kevinmora94** [kevinmora94/gramaticapp#2]
change the cards and the buttons colors for some cool colors in "La coma" tag

Some easy issues for hacktoberfest beginners

**Comment by sagarchoudhary96** [comment]
@kevinmora94 what's colors you want for the buttons?

**Comment by kevinmora94** [comment]
maybe some blue that works with the red in the footer

**Comment by paresh-agrawal** [comment]
@kevinmora94 I am a designer and developer may be I can help you with better color scheme.

**Comment by kevinmora94** [comment]
@paresh-agrawal cool, could you do a pull request? and I will check it out
Remember, this a easy issue for hacktoberfest first tries so you don't need to complicate yourself :)

**Comment by francistaberdo** [comment]
I can help you with this as well.
